config/routes.rb
Rails.application.routes.draw do
  get 'cars/new'
  get 'cars/edit'
  get 'cars/id'
  get '/about', to: 'misc#about', as: 'about'
  get '/contact', to: 'misc#contact', as: 'contact'
  get '/FAQ', to: 'misc#FAQ', as: 'faq'
  get '/terms', to: 'misc#terms', as: 'terms'
  get '/Index', to: 'misc#Index', as: 'index2'
  resources :posts do
    resources :comments
  end
  resources :cars


  #
  # get 'posts/', to: 'posts#index', as: 'home'
  # get 'post/new', to: 'posts#new', as: 'new'
  # get 'posts/:id', to: 'posts#show', as: 'show'
  # get 'posts/:id/edit', to: 'posts#edit', as: 'edit'
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments

  validates :title, length: {maximum: 15, message: "Max length is 15 chars"}
  validates :title, :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index2
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def edit
    @car = Car.find(params[:id])
  end

  def create

  end

  def id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = Comment.all

  end

  def create
    # @post = Post.find(params[:post_id])
    # comment_params = params.require(:comment).permit(:name, :content)
    @comment = @post.comments.create(comment_params)
    redirect_to @post
  end

  def edit
    # @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    # @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    # comment_params = params.require(:comment).permit(:name, :content)
    @comment.update(comment_params)
    redirect_to @post
  end

  def comment_params
    comment_params = params.require(:comment).permit(:name, :content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post
  end
end

app/controllers/misc_controller.rb
class MiscController < ApplicationController
  def about
  end

  def contact
  end

  def FAQ
  end

  def terms
  end

  def Index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    post_params = params.require(:post).permit(:title, :body, :author)
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html{redirect_to @post, notice: 'Post was created'}
      else
        format.html{render :new}
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    post_params = params.require(:post).permit(:title, :body, :author)
    respond_to do |format|
      if @post.update(post_params)
        format.html{redirect_to @post, notice: 'Post was Updated'}
      else
        format.html{render :new}
      end
    end
    # redirect_to @post
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/misc_helper.rb
module MiscHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/cars/edit.html.erb
<h1>Cars#edit</h1>
<p>Find me in app/views/cars/edit.html.erb</p>

app/views/cars/id.html.erb
<h1>Cars#id</h1>
<p>Find me in app/views/cars/id.html.erb</p>

app/views/cars/new.html.erb
<h1>Cars#new</h1>
<p>Find me in app/views/cars/new.html.erb</p>

app/views/comments/_comment.html.erb
<b><%= comment.name %>:</b>
<p><%= comment.content %></p>
<button type="button" name="button">
  <%= link_to "Edit", edit_post_comment_path(@post, comment) %>
</button>
<button type="button" name="button">
  <%= link_to "Delete", [@post, comment], method: :delete %>
</button>
<hr>

app/views/comments/_form.html.erb
<%= form_for([@post, comment]) do |f| %>
  <br>
  <div class="field">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :content %>
    <br>
    <%= f.text_area :content %>
  </div>
  <br>
  <div>
    <%= f.submit %>
  </div>
<% end  %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<div class="content">
  <%= render partial: "form", locals: {comment: @comment} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <%= render 'layouts/partials/navbar' %>  
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_navbar.html.erb
<%= link_to 'About', about_path %>
<%= link_to 'contact', contact_path %>
<%= link_to 'FAQ', faq_path %>
<%= link_to 'Terms', terms_path %>
<%= link_to 'Index', index2_path %>
<%= link_to 'Posts', posts_path %>
<%= link_to 'Cars', cars_path %>

app/views/misc/FAQ.html.erb
<h1>Misc#FAQ</h1>
<p>Find me in app/views/misc/FAQ.html.erb</p>

app/views/misc/Index.html.erb
<h1>Index</h1>
<p>Find me in app/views/misc/Index.html.erb</p>

app/views/misc/about.html.erb
<div class="content">
  <h1>About</h1>
  <p>Find me in app/views/misc/about.html.erb Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

app/views/misc/contact.html.erb
<div class="content">
  <h1>Contact</h1>
  <p>Find me in app/views/misc/contact.html.erb Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

app/views/misc/terms.html.erb
<h1>Misc#terms</h1>
<p>Find me in app/views/misc/terms.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
<% if post.errors.any?  %>
  <h2><%= pluralize(post.errors.count, 'error')a %> to fix</h2>
  <ul>
    <% post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <br>
  <div class="field">
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= f.label :body %>
    <br>
    <%= f.text_area :body %>
  </div>
  <br>
  <div class="field">
    <%= f.label :author %>
    <br>
    <%= f.text_field :author %>
  </div>
  <br>
  <div>
    <%= f.submit %>
  </div>
<% end  %>

app/views/posts/edit.html.erb
<div class="navbar">
  <%= link_to 'Home', posts_path %>
  <%= link_to 'Return to post', post_path %>
</div>

<h1><%= "Edit page for #{@post.id}" %></h1>

<div class="content">
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<h1>Welcome to my Blog</h1>

<div class="content">
  <h2>Blog Posts</h2>
  <%= link_to "Create a New Post", new_post_path %>

  <% @posts.each do |post|  %>
    <hr>
    <!-- <h3><%= post.title %></h3> -->
    <h2><%= link_to "#{post.title}", post %></h2>
    <p><%= post.body %></p>

    <cite><%= post.author %></cite>
    <br>
    <br>
    <button type="button" name="button">
      <%= link_to 'Edit Post', edit_post_path(post) %>
    </button>
    <button type="button" name="button">
      <%= link_to 'Delete Post', @post, method: :delete %>
    </button>

  <% end %>
</div>

app/views/posts/new.html.erb
<div class="navbar">
  <%= link_to 'Home', posts_path %>
</div>
<h1>Create A New post</h1>

<div class="content">
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="navbar">
  <%= link_to 'Posts Home', posts_path %>
  <%= link_to 'New Post', new_post_path %>
</div>



<div class="content">
  <p id="notice"><%= notice %></p>
  <h1><%= @post.title %></h1>
  <h4><%= "By #{@post.author}" %></h4>
  <p><%= @post.body %></p>
  <button type="button" name="button">
    <%= link_to 'Edit Post', edit_post_path %>
  </button>
  <button type="button" name="button">
    <%= link_to 'Delete Post', @post, method: :delete %>
  </button>
</div>

<hr>
<div class="comments">
  <h3>Comment Section</h3>
  <%= render partial: 'comments/comment', collection: @post.comments, as: :comment %>
</div>

<hr>
<div class="content">
  <h3>Add Comment</h3>
  <%= render partial: "comments/form", locals: { comment: @post.comments.new } %>
</div>